//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentTeacherCollabAppp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string Status { get; set; }
        public int Category_id { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
